// ADServeMimeCodegen — generates `Sources/ADServeCore/Generated/MIMEDatabase.swift` from the vendored
// jshttp/mime-db snapshot (see NOTICE). Following the family codegen pattern (ADHTML's ADHTMLCodegen,
// ADR-0009): a standalone dev tool run BY HAND, its output committed + reviewable in diffs — never a
// build plugin, so consumers of the ADServe libraries never run codegen. Foundation-only; not a product.
//
//   swift run ADServeMimeCodegen [out-path]      # default: Sources/ADServeCore/Generated/MIMEDatabase.swift
//
// The output carries `// swift-format-ignore-file` + `// swiftlint:disable all`, so no post-format step
// is needed (the generated switch is intentionally long).
//
// The table is emitted as a generated string `switch` (the compiler lowers it to a hashed jump): a
// direct compile-time lookup with NO runtime table-building or parsing. Switch cases type-check
// independently, so this compiles fast — whereas a ~1200-entry `[String: Entry]` dictionary literal
// (one giant expression) regressed the build to ~a minute.

import Foundation

/// One raw mime-db record (the fields we use).
struct MimeDBEntry: Decodable {
    let source: String?
    let charset: String?
    let compressible: Bool?
    let extensions: [String]?
}

/// Source preference when one extension maps to several media types — mirrors the `mime-types` package
/// (IANA is canonical, then Apache, then nginx, then unsourced).
func sourceRank(_ source: String?) -> Int {
    switch source {
        case "iana": return 3
        case "apache": return 2
        case "nginx": return 1
        default: return 0
    }
}

guard let url = Bundle.module.url(forResource: "mime-db", withExtension: "json"),
    let data = try? Data(contentsOf: url)
else {
    fatalError("ADServeMimeCodegen: cannot locate the vendored mime-db.json resource")
}
let db = try JSONDecoder().decode([String: MimeDBEntry].self, from: data)

/// The resolved table value for one extension.
struct Resolved {
    let type: String
    let charset: String?
    let compressible: Bool
}
var byExtension: [String: Resolved] = [:]
var winningRank: [String: Int] = [:]

// Iterate types in a stable order so ties resolve deterministically (→ reproducible output).
for type in db.keys.sorted() {
    guard let entry = db[type], let extensions = entry.extensions, !extensions.isEmpty else { continue }
    let rank = sourceRank(entry.source)
    // Charset policy: honor an explicit mime-db charset; else default `text/*` to utf-8 (the modern web
    // default — mime-db omits it for text/html); else no charset (binary/image/font/…).
    let charset = entry.charset?.lowercased() ?? (type.hasPrefix("text/") ? "utf-8" : nil)
    let resolved = Resolved(type: type, charset: charset, compressible: entry.compressible ?? false)
    for ext in extensions {
        let key = ext.lowercased()
        if rank > (winningRank[key] ?? -1) {
            winningRank[key] = rank
            byExtension[key] = resolved
        }
    }
}

// One `case "<ext>": return Entry(...)` per extension, sorted for a stable, reviewable diff.
let cases = byExtension.keys.sorted()
    .compactMap { ext -> String? in
        guard let resolved = byExtension[ext] else { return nil }
        let charsetLiteral = resolved.charset.map { "\"\($0)\"" } ?? "nil"
        return "        case \"\(ext)\":\n"
            + "            return Entry(type: \"\(resolved.type)\", charset: \(charsetLiteral), "
            + "compressible: \(resolved.compressible))"
    }

// The bare media types mime-db marks `compressible: true` — the type-keyed compressibility the on-the-fly
// response compressor consults (the extension table above is keyed by extension, but a response carries a
// Content-Type, not a filename). One `case` per compressible type, sorted for a stable diff.
let compressibleTypes = db.keys.filter { db[$0]?.compressible == true }.sorted()
let compressibleCases = compressibleTypes.map { "        case \"\($0)\": return true" }

// Build the file from a joined array of lines (not a `"""` literal) so the emitted columns are exact +
// deterministic, and `main.swift` itself stays free of multiline-string indentation churn. The format +
// lint gates are disabled in-file: the generated switch is intentionally long (a fast hashed jump).
let preamble = [
    "// swift-format-ignore-file",
    "// swiftlint:disable all",
    "// GENERATED by ADServeMimeCodegen from a vendored jshttp/mime-db snapshot (v1.54.0) — do NOT edit",
    "// by hand. Regenerate: `swift run ADServeMimeCodegen`. Provenance + the MIT license are in",
    "// Sources/ADServeMimeCodegen/NOTICE.",
    "",
    "/// The authoritative file-extension → media-type table, generated from jshttp/mime-db (the IANA +",
    "/// Apache + nginx aggregate). Backs `MediaType(fileExtension:)` + the `Static` content-type lookup;",
    "/// the `compressible` flag drives precompressed-variant (`.br`/`.gz`) negotiation. Where an",
    "/// extension mapped to several types, the highest source priority (iana > apache > nginx) won.",
    "enum MIMEDatabase {",
    "    /// One resolved media type: the bare type, an optional charset (`text/*` defaults to utf-8),",
    "    /// and whether the payload is worth compressing.",
    "    struct Entry: Sendable, Equatable {",
    "        let type: String",
    "        let charset: String?",
    "        let compressible: Bool",
    "    }",
    "",
    "    /// The media type for a lowercase, dot-free file extension, or `nil`. A generated string switch",
    "    /// — lowered to a hashed jump: a direct compile-time lookup, no runtime parsing"
        + " (\(cases.count) extensions).",
    "    static func entry(forExtension ext: String) -> Entry? {",
    "        switch ext {"
]
.joined(separator: "\n")

// Close `entry(forExtension:)`, then the type-keyed `isCompressible(type:)` switch (default false — an
// unknown type is never compressed), then the enum.
let middle = [
    "        default:",
    "            return nil",
    "        }",
    "    }",
    "",
    "    /// Whether the on-the-fly response compressor should compress this BARE media type (mime-db's",
    "    /// `compressible` flag; \(compressibleTypes.count) types). Pass the type with no parameters —",
    "    /// strip `; charset=…` first. An unknown type returns `false` (never compressed, the safe default).",
    "    static func isCompressible(type: String) -> Bool {",
    "        switch type {"
]
.joined(separator: "\n")
let footer = "        default:\n            return false\n        }\n    }\n}\n"

let outPath =
    CommandLine.arguments.count > 1
    ? CommandLine.arguments[1] : "Sources/ADServeCore/Generated/MIMEDatabase.swift"
let body =
    preamble + "\n" + cases.joined(separator: "\n") + "\n" + middle + "\n"
    + compressibleCases.joined(separator: "\n") + "\n" + footer
try body.write(toFile: outPath, atomically: true, encoding: .utf8)
print(
    "ADServeMimeCodegen: wrote \(cases.count) extensions + \(compressibleTypes.count) compressible types "
        + "→ \(outPath)")
